### ISSUE TITLE
Add container link scss implementation

### ISSUE THREAD

**Issue by alexander-schranz** [massiveart/web-js#25]
Sometimes a whole container should be linked this can be done by adding the following mixin to our toolset:

```scss
@mixin containerLink() {
    &::after {
        content: '';
        position: absolute;
        height: 100%;
        left: 0;
        top: 0;
        width: 100%;
    }
}
```

**Usage: (https://jsfiddle.net/p9zcoqm5/10/)**

```html
<article class="test">
     <img src="http://placehold.it/200x100" alt="test">
 
     <h3>Title</h3>

     <a href="/test" class="test__link">
            Link
     </a>

     <a class="test__author"  href="/author">
            Author
     </a>
</article>
```

```scss
.test {
    position: relative;
    background: red;
    width: 200px;
}

.test__link {
    @include containerLink();
}

.test__author {
     position: relative;
     z-index: 10; // not needed when element is after link
}
```
